### ISSUE TITLE
Missing plugin exception

### ISSUE THREAD

**Issue by KonstantinKolesnik** [andyduke/filesystem_picker#1]
Android 10
FilesystemPicker.open(.....

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)

MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)

**Comment by andyduke** [comment]
@KonstantinKolesnik Please report a complete dump of the error.

**Comment by KonstantinKolesnik** [comment]
D/ViewRootImpl@3478631[MainActivity](12202): ViewPostIme pointer 0
D/ViewRootImpl@3478631[MainActivity](12202): ViewPostIme pointer 1
I/flutter (12202): [GOING TO ROUTE] null
E/flutter (12202): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
E/flutter (12202): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (12202): <asynchronous suspension>
E/flutter (12202): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (12202): #2      PermissionHandler.requestPermissions (package:permission_handler/src/permission_handler.dart:85:30)
E/flutter (12202): #3      _FilesystemPickerState._requestPermission (package:filesystem_picker/src/picker_page.dart:112:35)
E/flutter (12202): #4      _FilesystemPickerState.initState (package:filesystem_picker/src/picker_page.dart:106:5)
E/flutter (12202): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter (12202): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (12202): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (12202): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (12202): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (12202): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (12202): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (12202): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (12202): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (12202): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (12202): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (12202): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (12202): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (12202): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (12202): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (12202): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (12202): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (12202): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (12202): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (12202): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (12202): #25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter (12202): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (12202): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (12202): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
E/flutter (12202): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (12202): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (12202): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (12202): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (12202): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (12202): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (12202): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (12202): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (12202): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (12202): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (12202): #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter (12202): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (12202): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (12202): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
E/flutter (12202): #43     ComponentElement.mount (package:flutter/src/widgets/
W/maestro.ecosca(12202): Reducing the number of considered missed Gc histogram windows from 103 to 100

**Comment by KonstantinKolesnik** [comment]
![Screenshot_20200514-184902](https://user-images.githubusercontent.com/2512064/81956301-cdd42980-9613-11ea-8096-01768691ecbe.jpg)

**Comment by andyduke** [comment]
@KonstantinKolesnik Have you specified permissions in AndroidManifest.xml?
```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>```

**Comment by KonstantinKolesnik** [comment]
Yes, sure

**Comment by andyduke** [comment]
Does your project use AndroidX?

**Comment by andyduke** [comment]
Try migrating to AndroidX: https://flutter.dev/docs/development/androidx-migration

**Comment by KonstantinKolesnik** [comment]
I have these in my gradle.properties

org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true

Is it correct?

**Comment by andyduke** [comment]
Yes, see an example: https://github.com/andyduke/filesystem_picker/tree/master/package/example
