### ISSUE TITLE
Remove dependency on permission_handler

### ISSUE THREAD

**Issue by hpoul** [andyduke/filesystem_picker#10]
Is there a reason to make this package depending on `permission_handler`? the filesystem_picker is very much useful without access to external storage (android) or the documents/photo/.. storage (ios).
It is a bit annoying to have to disable all iOS permissions in my `Podfile` (so that it is not rejected by the app store) and/or potentially adding permissions to my app without realising it.

Would you be open for removing this dependency? It's just a one liner for the embedding app if those are really required. (And the calling app is the only who knows which permissions are required, if any).

**Comment by andyduke** [comment]
> Is there a reason to make this package depending on `permission_handler`? the filesystem_picker is very much useful without access to external storage (android) or the documents/photo/.. storage (ios).
> It is a bit annoying to have to disable all iOS permissions in my `Podfile` (so that it is not rejected by the app store) and/or potentially adding permissions to my app without realising it.
> 
> Would you be open for removing this dependency? It's just a one liner for the embedding app if those are really required. (And the calling app is the only who knows which permissions are required, if any).

It probably makes sense.  Maybe add a callback to check access permissions?

**Comment by hpoul** [comment]
@andyduke at least the way it is implemented now a callback would be pretty useless.. right now it just calls request permission in initState, and never again.. so callers could just as easy call it directly before ever starting the filesystem picker 

The only problem would probably be when permissions are missing.. but i think to check this, one could simply try to do a `listFiles`.. or maybe there should just be documentation that the picker needs permission to access the `rootDirectory` (duh) and it's the callers responsibility to ask for it.. 
(Imo in most cases there is no reason for this.. if you need access to external files, users should use a native file picker like [file_picker_writable](https://pub.dev/packages/file_picker_writable) (if i might plug my own plugin :) ) .. a flutter based picker almost only makes sense for "internal" file locations like the apps own documents directory) or at least a pretty narrow known location..

**Comment by andyduke** [comment]
> 
> 
> @andyduke at least the way it is implemented now a callback would be pretty useless.. right now it just calls request permission in initState, and never again.. so callers could just as easy call it directly before ever starting the filesystem picker
> 
> The only problem would probably be when permissions are missing.. but i think to check this, one could simply try to do a `listFiles`.. or maybe there should just be documentation that the picker needs permission to access the `rootDirectory` (duh) and it's the callers responsibility to ask for it..
> (Imo in most cases there is no reason for this.. if you need access to external files, users should use a native file picker like [file_picker_writable](https://pub.dev/packages/file_picker_writable) (if i might plug my own plugin :) ) .. a flutter based picker almost only makes sense for "internal" file locations like the apps own documents directory) or at least a pretty narrow known location..

I added a permission request to the picker just to update the status and display a message when no permissions were granted. So I think it's worth adding a callback instead of permission_handler.
