### ISSUE TITLE
Nothing is returned when window is closed using the button in the upper left corner

### ISSUE THREAD

**Issue by schwenkreis** [andyduke/filesystem_picker#12]
filesystem_picker just closes the window (pop()) without  invoking the completer.

**Comment by andyduke** [comment]
@schwenkreis This is as it should be, this button works like "Cancel".

**Comment by schwenkreis** [comment]
Well, the problem is that if you are using the approach of your example:
String path = await FilesystemPicker.open(
  title: 'Open file',
  context: context,
  rootDirectory: rootPath,
  fsType: FilesystemType.file,
  folderIconColor: Colors.teal,
  allowedExtensions: ['.txt'],
  fileTileSelectMode: FileTileSelectMode.wholeTile,
);
, then it will never return because the Future is never fulfilled. 
Can you please let me know how the caller should know that the oicker was closed? Furthermore, there is still an open thread waiting ...

Cheers
Friedemann

**Comment by andyduke** [comment]
> 
> 
> Well, the problem is, that if you are using the approach of your example:
> String path = await FilesystemPicker.open(
> title: 'Open file',
> context: context,
> rootDirectory: rootPath,
> fsType: FilesystemType.file,
> folderIconColor: Colors.teal,
> allowedExtensions: ['.txt'],
> fileTileSelectMode: FileTileSelectMode.wholeTile,
> );
> , then it will never return because the Future is never fulfilled.
> Can you please let me know how the caller should know that the picker was closed? Furthermore, there is still an open thread waiting ...
> 
> Cheers
> Friedemann

I understand what you are talking about: `FilesystemPicker.open` should return null if the user just closed the Picker screen. I will make improvements in the near future.

**Comment by andyduke** [comment]
@schwenkreis I fixed this bug, now when the user tap on the Cancel button or press the Back button on the device `FilesystemPicker.open` returns null.

**Comment by schwenkreis** [comment]
Fantatstic! Thanks a lot for the support!
