### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by selvam920** [andyduke/filesystem_picker#21]
i'm getting below error
Target of URI doesn't exist: 'package:filesystem_picker/filesystem_picker.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist

used 
 filesystem_picker: 2.0.0-nullsafety.0
in pubspec.yaml

**Comment by andyduke** [comment]
@selvam920 Please provide the output of the `flutter doctor -v`.
