### ISSUE TITLE
Add option to display the picker as Dialog

### ISSUE THREAD

**Issue by escamoteur** [andyduke/filesystem_picker#24]
Hi,

many thanks for this package. A native Flutter File Picker is a great idea. For Desktop or Tablet sized screens it would be nice to have an option so that the picker doesn't get displayed as full screen but as a dialog.

Cheers
Thomas

**Comment by andyduke** [comment]
@escamoteur Please try the [beta version 3.0](https://pub.dev/packages/filesystem_picker/versions/3.0.0-beta.1), will it solve your problem?
