### ISSUE TITLE
FileSystem Picker all the time starts from the root of the file repository

### ISSUE THREAD

**Issue by piratkin** [andyduke/filesystem_picker#26]
FileSystem Picker all the time starts from the root of the file repository

The rootDirectory parameter limits navigation, it would be nice to have two variables. One pointed to the storage root, and the other to the place, relative to the root, where the file selection dialog should be provided.

In one variable it will be possible to store the storage root, and in another variable, it will be possible to transfer the last location from which the file was loaded.

The problem is that if the nesting, relative to the root of the file storage, is large, then you have to perform many transitions to the desired location.

You don't need to change the API much, you can just add another variable for example:

```dart
  Directory? stateDirectory;
  static Future<String?> open({
    ...
    required Directory rootDirectory,
    stateDirectory,
    ...
  }) ... 
 {
   if (stateDirectory == null)
     stateDirectory = rootDirectory;
 }

```

**Comment by andyduke** [comment]
@piratkin You should not think of the `rootDirectory` parameter as the root of the entire filesystem on the device, but as the folder that will appear in the `FileSystemPicker`. If you want to show, for example, the `/Documents` folder, then you can pass it to the `rootDirectory` parameter, and not the root of entire filesystem `/`.

To show the last selected folder, you can save it in your application and pass it to the `rootDirectory` parameter.

**Comment by piratkin** [comment]
If you use the last directory used by the user as rootDirectory, then it will hide all parent subdirectories. As a result, the user will only be able to move up the catalog tree.

**Comment by UNIcodeX** [comment]
> @piratkin You should not think of the `rootDirectory` parameter as the root of the entire filesystem on the device, but as the folder that will appear in the `FileSystemPicker`. If you want to show, for example, the `/Documents` folder, then you can pass it to the `rootDirectory` parameter, and not the root of entire filesystem `/`.
> 
> To show the last selected folder, you can save it in your application and pass it to the `rootDirectory` parameter.

how does one pass in the platform specific Documents folder? `rootDirectory: Directory("/Documents"),` does not work.

**Comment by andyduke** [comment]
@piratkin Please try the [beta version 3.0](https://pub.dev/packages/filesystem_picker/versions/3.0.0-beta.1), will it solve your problem?
