### ISSUE TITLE
[Future Request] Provide choice to disable showing hidden files.

### ISSUE THREAD

**Issue by VergeDX** [andyduke/filesystem_picker#27]
I searched for the whole repo and seems there is no way to hide showing the hidden files.
Am I miss something...? Or I will try to make a PR to implement this...

**Comment by andyduke** [comment]
@VergeDX By what criterion do you propose to determine that the file is "hidden"?

**Comment by VergeDX** [comment]
Wikipedia has a item for it: [Hidden_file_and_hidden_directory](https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory) : )
The criterion are not same on Unix & Windows, but it can be implemented.

**Comment by andyduke** [comment]
@VergeDX This concept differs significantly in different operating systems, so it is difficult to make a universal solution. The only thing that can be done is a callback to filter the list of files and directories.

**Comment by andyduke** [comment]
@VergeDX Please try the [beta version 3.0](https://pub.dev/packages/filesystem_picker/versions/3.0.0-beta.1), will it solve your problem?

**Comment by VergeDX** [comment]
Good job! We use other library already :laughing:
