### ISSUE TITLE
Accessing Internal Root Directory fails

### ISSUE THREAD

**Issue by nemoryoliver** [andyduke/filesystem_picker#3]
```
I/flutter ( 6564): FileSystemException: Directory listing failed, path = '/storage/emulated/0/' (OS Error: Permission denied, errno = 13)
```

Even with granted permissions, I still get that error, but only to devices without an external SD Card support. I hope there's a workaround. Thanks for your great work!

**Comment by andyduke** [comment]
I think that without rooting, you will not be able to access the root of the internal storage from the application. This is a limitation of Android.

**Comment by nemoryoliver** [comment]
> I think that without rooting, you will not be able to access the root of the internal storage from the application. This is a limitation of Android.

Thanks. But I mean even accessing the root directory of Downloads it's not working and getting the above error.

'/storage/emulated/0/Download/' using ext_storage package

**Comment by andyduke** [comment]
Could you provide full console output with errors?
What version of Android is used? Is this a real device or an emulator?

**Comment by nemoryoliver** [comment]
> Could you provide full console output with errors?
> What version of Android is used? Is this a real device or an emulator?

The only significant error is what I posted above, using a real device, a OnePlus 8. But this happens to other devices too especially devices without an SD Card slot.

**Comment by andyduke** [comment]
What version of Android is used?

**Comment by nemoryoliver** [comment]
Android 10

**Comment by andyduke** [comment]
I think this problem is due to changes in Android 10. See https://developer.android.com/about/versions/10/privacy/changes#top-changes
