### ISSUE TITLE
Error: The getter 'title' isn't defined for the class 'TextTheme'.

### ISSUE THREAD

**Issue by daybson** [andyduke/filesystem_picker#31]
After upgrade flutter 2.2.3 to 2.5:

/C:/Users/daybs/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/filesystem_picker-1.0.4/lib/src/picker_page.dart:184:63: Error: The getter 'title' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'title'.
                    color: AppBarTheme.of(context).textTheme?.title?.color ??

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [versÃ£o 10.0.19043.1237], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.60.1)
[√] Connected device (4 available)

• No issues found!

**Comment by andyduke** [comment]
@daybson Use version [2.0.0-nullsafety.0](https://pub.dev/packages/filesystem_picker/versions/2.0.0-nullsafety.0)
