### ISSUE TITLE
New folder button

### ISSUE THREAD

**Issue by godalming123** [andyduke/filesystem_picker#37]
When the user is picking a file it is a bad UX if they have to go to a file manager to create a folder and so therfor I think you should add an add folder button as either one on the bottom bar or a FAB

**Comment by andyduke** [comment]
@godalming123 At the moment, I am in the process of the `FileSystemPicker` refactor, adding significant possibilities for customizing and extending Picker.

**Comment by godalming123** [comment]
Great!

**Comment by andyduke** [comment]
@godalming123 Please try the [beta version 3.0](https://pub.dev/packages/filesystem_picker/versions/3.0.0-beta.1), will it solve your problem?

**Comment by godalming123** [comment]
No longer run into this issue but that looks great will use next time I need a folder picker!
