### ISSUE TITLE
Compatibility issue with Flutter 3.0.0 - Warning in breadcrumbs.dart

### ISSUE THREAD

**Issue by pmah8** [andyduke/filesystem_picker#38]
After upgrading to Flutter 3.0.0 I am getting this warning when building/running my app

flutter/.pub-cache/hosted/pub.dartlang.org/filesystem_picker-2.0.0/lib/src/breadcrumbs.dart:53:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/Peter_Data/localdev/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) => _scrollToEnd());

It runs ok but the warning does prevent building an iOS archive due to getting a nonzero exit code during the build process.

**Comment by andyduke** [comment]
@pmah8 Fixed in version [2.0.1](https://pub.dev/packages/filesystem_picker/versions/2.0.1).
