### ISSUE TITLE
can't see files in the folder and select the folder anymore

### ISSUE THREAD

**Issue by john9880795976** [andyduke/filesystem_picker#39]
In version 2.0.0 you could set fsType: FilesystemType.all, enter a folder, SEE THE LIST OF FILES IN THE FOLDER, and select the folder because there was a button on the bottom.
In 3.0.0 with fsType: FilesystemType.all  you can see the files but there is no button to select the folder.  You only have the button for FilesystemType.folder.   Most people like to see the files before selecting the folder. 
So just change from version 2 to 3 in the pubspec, and the button is not there anymore with FilesystemType.all.    I sent Andy the screenshots, button not there.

**Comment by andyduke** [comment]
@john9880795976 Please provide the minimum code that reproduces the problem.

**Comment by john9880795976** [comment]
His Andy,

Nothing to it really.
You know the button on the bottom that says 'select this folder'?  
If you use fsType: FilesystemType.all that button no longer shows up on
In the new version.  That is why I have to stay with the old version.

That way you can see the files in the folder and know it is the right folder before selecting.
  


 String? selectedPath = await FilesystemPicker.open(
      title: 'Select music folder',
      context: context,
      // rootDirectory: startPath!,
      rootDirectory: startPath!,
      fsType: FilesystemType.all,
      pickText: 'Select this folder',
      folderIconColor: borderColor,
      //  sub dirs?
      //  allowedExtensions: ["mp3"],
      requestPermission: () async => await Permission.storage.request().isGranted,
    );

**Comment by andyduke** [comment]
This button for `FilesystemType.all` was not displayed before. So nothing has changed in the new version.
Can you give more details, what is your problem?

**Comment by john9880795976** [comment]
cupertino_icons: ^1.0.2
  http:
  rxdart:
  uuid:
  path_provider: ^2.0.10
  connectivity_plus: ^2.3.0
  intl: 0.17.0
  sqflite: ^2.0.2+1
  filesystem_picker: ^2.0.0
  permission_handler: ^8.2.5
  flutter_paypal: ^0.0.8
  platform_device_id: ^1.0.1
  #crypto_keys: ^0.3.0
  hex: ^0.2.0
  basic_utils: ^4.4.3


This is what is in my pub spec

**Comment by andyduke** [comment]
Please provide the code for version 2.0 and a screenshot of the application, and the same for version 3.0, to understand the difference.

**Comment by john9880795976** [comment]
All I changed

filesystem_picker: ^3.0.0

Button gone.

**Comment by john9880795976** [comment]
All I’m saying is see the files and select the folder.
Can the new version do this?

Now you have all the code and the screenshot.
Thanks for your efforts.  I started this project a few years ago, just got back to it.
Flutter needs a good file picker!   You have the only one I can use still.
I still can’t change the color of the file icons so they can’t be seen here.
