### ISSUE TITLE
Change root on Windows?

### ISSUE THREAD

**Issue by seanocali** [andyduke/filesystem_picker#42]
On Mac and Linux you can set '/' as a root, but Windows how do you change to a different drive letter?

**Comment by andyduke** [comment]
@seanocali I can add a parameter with which you can pass a list of shortcuts (a list of file system paths, e.g. "C:\", "D:\" for Windows) that will appear first in the breadcrumb path hierarchy, as well as in the main list if rootDirectory is not set.

**Comment by andyduke** [comment]
@seanocali Have a look at version [4.0.0-beta.1](https://pub.dev/packages/filesystem_picker/versions/4.0.0-beta.1), will that fix your problem?
