### ISSUE TITLE
Does not work for android 13

### ISSUE THREAD

**Issue by sadiq61651** [andyduke/filesystem_picker#43]
Kindly update this package with permission, because it is not working for android 13.

**Comment by andyduke** [comment]
What exactly is not working for you in Android 13?  Can you provide more information?

**Comment by sadiq61651** [comment]
Hi thanks for the quick reply, I think because of the photo picker with
Android 13 this package does not work to access and read files in internal
storage.
I think the main reason is that "android.permission.READ_EXTERNAL_STORAGE"
no longer works in android 13.
Kindly test this package for android 13, and if there is any
permission(i.e: "READ_MEDIA_IMAGES" for reading images in android 13) aware
us from them in order to read pdf/test/word files from internal storage.

**Comment by andyduke** [comment]
Configuring file system permissions in an application is outside the scope of the filesystem_picker package.  You must do it yourself and specify the required path in the FileSystemPicker.  You can also request additional permissions from the user using the `requestPermission` callback.

**Comment by sadiq61651** [comment]
Like what kind of Permission request we need to perform filesystem_picker
operation sucessfully in Android 13.

**Comment by andyduke** [comment]
See Android guides, for example https://developer.android.com/training/data-storage/manage-all-files
