### ISSUE TITLE
Change Root on Android

### ISSUE THREAD

**Issue by davidpbrown** [andyduke/filesystem_picker#44]
Could do with an option to allow Android users to navigate between internal and external storage - where that exists.
File Managers seem to have a toggle for that difference.

It would be useful then to have the breadcrumb updated to reflect that (Internal/External).

thanks!

**Comment by andyduke** [comment]
@davidpbrown Look at version [4.0.0-beta.1](https://pub.dev/packages/filesystem_picker/versions/4.0.0-beta.1), it introduced the ability to use multiple root paths. Is it right for you?

**Comment by davidpbrown** [comment]
Wonderful.. it works very well.
There is one small glitch.. on the first pass the second breadcrumb is set as rootName, and oddly that persists if you go back and forward from the shortcuts back to the first shortcut but it stops and corrects that first shortcut's breadcrumb, if the second shortcut is used once.

**Comment by andyduke** [comment]
@davidpbrown Can you take screenshots of this issue?

**Comment by davidpbrown** [comment]
![1](https://user-images.githubusercontent.com/1708690/211433102-a9c3374f-05a7-4b44-b9a0-229d94e8180c.png)
![2](https://user-images.githubusercontent.com/1708690/211433105-16c17321-6b4a-41aa-ae6c-8f4891c50804.png)
![3](https://user-images.githubusercontent.com/1708690/211433109-8d4cff3c-1566-49b0-800d-6e9e0d0e63d0.png)
Attached 1 -> 2 -> 3

There is also something wrong with the parents button, if you go into a directory and up again using the ^.. you get a long trail of breadcrumbs that suggests error path does not exist.. again a snap of that attached
![also4](https://user-images.githubusercontent.com/1708690/211433241-2bfdf475-f583-46c2-a1a0-1e6bd6ad6533.png)

**Comment by andyduke** [comment]
@davidpbrown Can you share minimal code that reproduces the issue?

**Comment by seanocali** [comment]
I ran into something similar, I'll check out 4.0 beta as soon as I can. Thanks for making this BTW. The other package uses native OS pickers which does not support gamepad/remote functionality on desktops, something I personally need.

**Comment by davidpbrown** [comment]
There is nothing beyond the move from v3 to v4 and that inclusion of shortcuts for reproducing these.
This is obviously on Linux and I've not checked Android.

It seems for the parent button is just forgetting or defaulting the context and dumping to the location of the executable.

As for the second breadcrumb=rootName on first pass until second breadcrumb I guess that should be apparent in the code of whatever the second breadcrumb is doing the first has to learn.
```
      String? path = await FilesystemPicker.open(
        title: 'Select Folder',
        context: context,
        rootDirectory: rootPath!,
        rootName: '||',
        fsType: FilesystemType.folder,
        pickText: 'Select this folder',
        folderIconColor: Colors.teal,
        fileTileSelectMode: FileTileSelectMode.wholeTile,
        shortcuts: [
          FilesystemPickerShortcut(name: 'Downloads', path: preferences.directory),
          FilesystemPickerShortcut(name: '/', path: Directory('/')),
        ],
      );
```

**Comment by andyduke** [comment]
@davidpbrown Please tell me which path is contained in the `rootPath` variable and which one is in the `preferences.directory`?

**Comment by andyduke** [comment]
@davidpbrown You use `rootDirectory` in conjunction with `shortcuts`, you need to use one of them. Use `directory` to set the currently selected path.

Please try version [4.0.0-beta.2](https://pub.dev/packages/filesystem_picker/versions/4.0.0-beta.2), I made a tweak to allow you to specify the current directory relative to one of the shortcuts paths.

**Comment by davidpbrown** [comment]
Using ``directory`` as input for FilesystemPicker.open makes no obvious change to the breadcrumb and it still fixes only with a switch to second shortcut; beyond that switch the first shortcut then shows as expected.

The first pass shows the directory rootDirectory and its detail, it's just the breadcrumb for that is wrong; so, I don't understand the thought now to name it with a currently selected path.

There's just something odd on the first occasion, the breadcrumb is picking up on the rootName rather than the shortcut name..

**Comment by andyduke** [comment]
Does this also work incorrectly on version 4.0.0-beta.2?

**Comment by davidpbrown** [comment]
Yes.. upgraded before last comment. Didn't see any difference.

**Comment by andyduke** [comment]
@davidpbrown I will not reproduce your problem in version 4.0.0-beta.2. Can you post the minimal program code here (including main() so that it can be inserted into a newly created project in the main.dart file) when this problem is reproduced?
