### ISSUE TITLE
Go Up is broken on linux

### ISSUE THREAD

**Issue by madadam** [andyduke/filesystem_picker#50]
Clicking the Go Up button on Linux doesn't work. It shows error "Error loading file list: the path doesn't exist".

The reason is that the way the parent path is [calculated](https://github.com/andyduke/filesystem_picker/blob/master/package/lib/src/filesystem_list.dart#L187) is wrong because it doesn't preserve the leading slash. I wonder, why not just use [`Directory.parent`](https://api.dart.dev/stable/3.2.0/dart-io/FileSystemEntity/parent.html)?

**Comment by andyduke** [comment]
Could you provide the minimum required code to reproduce this issue?

**Comment by andyduke** [comment]
@madadam Your fix is already in the [release](https://pub.dev/packages/filesystem_picker/versions/4.1.0), thanks.
